const shopbtn = document.getElementById('shop')
const shopsubmenu = document.getElementById('shop-submenu')
const navbar = document.getElementById('navbar')
shopbtn.addEventListener('mouseover', () => chargingsubmenu.style.height= "0px")
shopbtn.addEventListener('mouseover', () => discoversubmenu.style.height= "0px")
shopbtn.addEventListener('mouseover', () => shopsubmenu.style.height= "250px" )
shopbtn.addEventListener('mouseover', () => navbar.style.backgroundColor="white")
//shopbtn.addEventListener('mouseleave', () => shopsubmenu.style.visibility="hidden")
//shopbtn.addEventListener('mouseleave', () => navbar.style.backgroundColor="transparent")
shopsubmenu.addEventListener('mouseover', () => shopsubmenu.style.height= "250px")
shopsubmenu.addEventListener('mouseover', () => navbar.style.backgroundColor="white")
shopsubmenu.addEventListener('mouseleave', () => shopsubmenu.style.height= "0px")
shopsubmenu.addEventListener('mouseleave', () => navbar.style.backgroundColor="transparent",navbar.style.transitionDelay="0.2s")

//const mainmenu = document.getElementById('main-menu')
//mainmenu.addEventListener('mouseover', () => navbar.style.backgroundColor = "white")
//mainmenu.addEventListener('mouseleave', () => navbar.style.backgroundColor = "transparent")

const discoverbtn = document.getElementById('discover')
const discoversubmenu = document.getElementById('discover-submenu')
discoverbtn.addEventListener('mouseover', () => shopsubmenu.style.height= "0px")
discoverbtn.addEventListener('mouseover', () => chargingsubmenu.style.height= "0px")
discoverbtn.addEventListener('mouseover', () => discoversubmenu.style.height= "300px")
discoverbtn.addEventListener('mouseover', () => navbar.style.backgroundColor="white")
discoversubmenu.addEventListener('mouseover', () => discoversubmenu.style.height= "300px")
discoversubmenu.addEventListener('mouseover', () => navbar.style.backgroundColor="white")
discoversubmenu.addEventListener('mouseleave', () => discoversubmenu.style.height= "0px")
discoversubmenu.addEventListener('mouseleave', () => navbar.style.backgroundColor="transparent")

const chargingbtn = document.getElementById('charging')
const chargingsubmenu = document.getElementById('charging-submenu')
chargingbtn.addEventListener('mouseover', () => discoversubmenu.style.height= "0px")
chargingbtn.addEventListener('mouseover', () => shopsubmenu.style.height= "0px")
chargingbtn.addEventListener('mouseover', () => chargingsubmenu.style.height= "0px")
chargingbtn.addEventListener('mouseover', () => chargingsubmenu.style.height= "350px")
chargingbtn.addEventListener('mouseover', () => navbar.style.backgroundColor="white")
chargingsubmenu.addEventListener('mouseover', () => chargingsubmenu.style.height= "350px")
chargingsubmenu.addEventListener('mouseover', () => navbar.style.backgroundColor="white")
chargingsubmenu.addEventListener('mouseleave', () => chargingsubmenu.style.height= "0px")
chargingsubmenu.addEventListener('mouseleave', () => navbar.style.backgroundColor="transparent")


const sidemenu = document.getElementById('side-menu')
sidemenu.addEventListener('mouseover', () => shopsubmenu.style.height= "0px")
sidemenu.addEventListener('mouseover', () => discoversubmenu.style.height= "0px")
sidemenu.addEventListener('mouseover', () => chargingsubmenu.style.height= "0px")
sidemenu.addEventListener('mouseover', () => navbar.style.backgroundColor="transparent")

